### ISSUE TITLE
Travis test will probably start failing for Python 3.2 and 3.3

### ISSUE THREAD

**Issue by antnieszka** [DataMedSci/beprof#100]
This happened today:
https://travis-ci.org/ant6/beprof/jobs/177465171
```
Collecting numpy (from -r requirements.txt (line 1))
  Using cached numpy-1.12.0b1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-pejdec/numpy/setup.py", line 34, in <module>
        raise RuntimeError("Python version 2.7 or >= 3.4 required.")
    RuntimeError: Python version 2.7 or >= 3.4 required.
```
@grzanka I think we should limit version of numpy in tests config...

**Comment by grzanka** [comment]
See https://github.com/pytrip/pytrip/issues/186 and corresponding PR
