### ISSUE TITLE
Division in place acts differently according to Python version

### ISSUE THREAD

**Issue by antnieszka** [DataMedSci/beprof#120]
This doctest works in py2.7, fails in 3.4.
```
        >>> c = Curve([[0, 0], [5, 5], [10, 10]], dtype=np.int)
        >>> c.rescale(-1, allow_cast=False)
        >>> print(c.y)
        [  0  -5 -10]
```
py3:
```py
Failed example:
    c.rescale(-1, allow_cast=False)
Exception raised:
    Traceback (most recent call last):
      File "/home/ant6/bin/pycharm-2016.3/helpers/pycharm/docrunner.py", line 140, in __run
        compileflags, 1), test.globs)
      File "<doctest curve.Curve.rescale[7]>", line 1, in <module>
        c.rescale(-1, allow_cast=False)
      File "/home/ant6/PycharmProjects/beprof/beprof/curve.py", line 109, in rescale
        self.y /= factor
    TypeError: ufunc 'true_divide' output (typecode 'd') could not be coerced to provided output parameter (typecode 'l') according to the casting rule ''same_kind''
```

With `allow_cast=True` both act the same and pass.

**Comment by grzanka** [comment]
Beware that in py3 you have two division operators: `//` and `/`

**Comment by antnieszka** [comment]
https://www.python.org/dev/peps/pep-0238/
```
    In Python 3.0, the classic division semantics will be removed; the
    classic division APIs will become synonymous with true division.
```
Probably we could use `from __future__ import division` to have true division, not classic in py2.7?

**Comment by antnieszka** [comment]
@grzanka this too probably should be resolved before release to pypy?

**Comment by grzanka** [comment]
Yes. I was thinking a bit more about it and the conclusion was that we should prefer floats over ints. 
Can you show an example how `from __future__ import division` works ?

**Comment by antnieszka** [comment]
According to this PEP: https://www.python.org/dev/peps/pep-0238/

>    - Classic division will remain the default in the Python 2.x
      series; true division will be standard in Python 3.0.

For Python 2:
>    - The future division statement, spelled "from \_\_future\_\_ import
      division", will change the / operator to mean true division
      throughout the module.

#### Classic division (default in Python 2)
```py
>>> 1 / 2          # integer truncation (floor division)
0
>>> 1.0 / 2.0      # returns real quotient (true division)
0.5
```

#### True division
```py
>>> from __future__ import division  # 2.2+-only
>>>
>>> 1 / 2               # returns real quotient
0.5
>>> 1.0 / 2.0           # returns real quotient
0.5
```
As said earlier - true division is default for Python 3.x, so is `/` used in our code.
More on topic: http://www.informit.com/articles/article.aspx?p=1439189

Oh, and `__future__` import is ignored in Python 3, so it will only affect beprof if running with Python 2.
