### ISSUE TITLE
Pip installation fails on windows

### ISSUE THREAD

**Issue by grzanka** [DataMedSci/beprof#32]
I downloaded beprof code from git and trying to install it locally using pip (Python3, anaconda, Windows 10), but installation fails:

```
C:\Users\User\PycharmProjects\beprof>pip install . --user
Processing c:\users\user\pycharmprojects\beprof
Collecting numpy>=1.10.4 (from beprof==0.1.0)
  Using cached numpy-1.10.4.tar.gz
Collecting scipy>=0.16.0 (from beprof==0.1.0)
  Using cached scipy-0.17.0.tar.gz
(......)
    error: Microsoft Visual C++ 10.0 is required (Unable to find vcvarsall.bat).

    ----------------------------------------
Command "C:\Users\User\Anaconda3\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\User\\AppData\\Local\\Temp\\pip-build-g_bmb6r6\\numpy\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\User\AppData\Local\Temp\pip-yddb2uuq-record\install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in C:\Users\User\AppData\Local\Temp\pip-build-g_bmb6r6\numpy
You are using pip version 7.1.2, however version 8.0.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

```

**Comment by grzanka** [comment]
I have Windows 10 with Python3.4 and numpy 1.9 installed using installer.
pip installation should fix following problem - change_domain method doesn't work, because it requires method introduced in numpy 1.10.
now there is complete mess

```
>>> import numpy as np
>>> np.version.version
'1.9.2'
>>> from beprof import curve
>>> c = curve.Curve([[0,0],[5,5],[10,10]])
>>> c.change_domain([1,2,3])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\User\PycharmProjects\beprof\beprof\curve.py", line 109, in change_domain
    obj = Curve(np.stack((domain, y), axis=1), **self.__dict__['metadata'])
AttributeError: 'module' object has no attribute 'stack'
```

**Comment by grzanka** [comment]
Scipy removed in #68 , this should be investigated again

**Comment by antnieszka** [comment]
Well, index error on fresh windows 10 installation:

```
ant6@DESKTOP-K5I4GEC MINGW64 ~/Downloads
$ pip install versioneer
Collecting versioneer
  Downloading versioneer-0.16-py2.py3-none-any.whl
Installing collected packages: versioneer
Successfully installed versioneer-0.16
You are using pip version 7.1.2, however version 8.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

ant6@DESKTOP-K5I4GEC MINGW64 ~/Downloads
$ pip install git+https://github.com/DataMedSci/beprof.git
Collecting git+https://github.com/DataMedSci/beprof.git
  Cloning https://github.com/DataMedSci/beprof.git to c:\users\ant6\appdata\local\temp\pip-wiw3w44q-build
    Complete output from command python setup.py egg_info:
    You are using pip version 7.1.2, however version 8.1.2 is available.
    You should consider upgrading via the 'python -m pip install --upgrade pip' command.
    Traceback (most recent call last):
      File "C:\Users\ant6\AppData\Local\Temp\pip-wiw3w44q-build\setup.py", line 21, in setup_versioneer
        import versioneer
    ImportError: No module named 'versioneer'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\ant6\AppData\Local\Temp\pip-wiw3w44q-build\setup.py", line 30, in setup_versioneer
        subprocess.check_output(["versioneer", "install"])
      File "c:\python34\lib\subprocess.py", line 607, in check_output
        with Popen(*popenargs, stdout=PIPE, **kwargs) as process:
      File "c:\python34\lib\subprocess.py", line 859, in __init__
        restore_signals, start_new_session)
      File "c:\python34\lib\subprocess.py", line 1114, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\ant6\AppData\Local\Temp\pip-wiw3w44q-build\setup.py", line 84, in <module>
        version=get_version(),
      File "C:\Users\ant6\AppData\Local\Temp\pip-wiw3w44q-build\setup.py", line 61, in get_version
        setup_versioneer()
      File "C:\Users\ant6\AppData\Local\Temp\pip-wiw3w44q-build\setup.py", line 42, in setup_versioneer
        if x.endswith("/versioneer")][0]
    IndexError: list index out of range

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\ant6\AppData\Local\Temp\pip-wiw3w44q-build
You are using pip version 7.1.2, however version 8.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

**Comment by antnieszka** [comment]
I don't get why importError...:

```
ant6@DESKTOP-K5I4GEC MINGW64 ~/Downloads
$ pip freeze
versioneer==0.16
```

**Comment by grzanka** [comment]
Try: `pip show -f versioneer`

**Comment by grzanka** [comment]
Probably an issue with path separator in `if x.endswith("/versioneer")][0]`

**Comment by antnieszka** [comment]
```
ant6@DESKTOP-K5I4GEC MINGW64 ~/Downloads
$ pip show -f versioneer
---
Metadata-Version: 2.0
Name: versioneer
Version: 0.16
Summary: Easy VCS-based management of project version strings
Home-page: https://github.com/warner/python-versioneer
Author: Brian Warner
Author-email: warner-versioneer@lothar.com
License: public domain
Location: c:\python34\lib\site-packages
Requires:
Files:
  ..\..\Scripts\versioneer
  versioneer-0.16.dist-info\DESCRIPTION.rst
  versioneer-0.16.dist-info\METADATA
  versioneer-0.16.dist-info\RECORD
  versioneer-0.16.dist-info\WHEEL
  versioneer-0.16.dist-info\metadata.json
  versioneer-0.16.dist-info\top_level.txt
You are using pip version 7.1.2, however version 8.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

**Comment by antnieszka** [comment]
```
ant6@DESKTOP-K5I4GEC MINGW64 ~/Downloads
$ python --version
Python 3.4.4
```

**Comment by grzanka** [comment]
Can you try with branch https://github.com/DataMedSci/beprof/tree/feature/42-windows-pip ?

**Comment by grzanka** [comment]
Quick fix here: https://github.com/DataMedSci/beprof/commit/13e0f28ca02473f39d15c1dbc9d7a44913fa2923

**Comment by antnieszka** [comment]
Well, I did this:

```
ant6@DESKTOP-K5I4GEC MINGW64 ~/Downloads
$ pip install git+https://github.com/DataMedSci/beprof.git@feature/42-windows-pip
Collecting git+https://github.com/DataMedSci/beprof.git@feature/42-windows-pip
  Cloning https://github.com/DataMedSci/beprof.git (to feature/42-windows-pip) to c:\users\ant6\appdata\local\temp\pip-gqpn5qkg-build
    Complete output from command python setup.py egg_info:
    You are using pip version 7.1.2, however version 8.1.2 is available.
    You should consider upgrading via the 'python -m pip install --upgrade pip' command.
    Traceback (most recent call last):
      File "C:\Users\ant6\AppData\Local\Temp\pip-gqpn5qkg-build\setup.py", line 21, in setup_versioneer
        import versioneer
    ImportError: No module named 'versioneer'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\ant6\AppData\Local\Temp\pip-gqpn5qkg-build\setup.py", line 30, in setup_versioneer
        subprocess.check_output(["versioneer", "install"])
      File "c:\python34\lib\subprocess.py", line 607, in check_output
        with Popen(*popenargs, stdout=PIPE, **kwargs) as process:
      File "c:\python34\lib\subprocess.py", line 859, in __init__
        restore_signals, start_new_session)
      File "c:\python34\lib\subprocess.py", line 1114, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\ant6\AppData\Local\Temp\pip-gqpn5qkg-build\setup.py", line 84, in <module>
        version=get_version(),
      File "C:\Users\ant6\AppData\Local\Temp\pip-gqpn5qkg-build\setup.py", line 61, in get_version
        setup_versioneer()
      File "C:\Users\ant6\AppData\Local\Temp\pip-gqpn5qkg-build\setup.py", line 48, in setup_versioneer
        subprocess.check_output([exe_path, "install"])
      File "c:\python34\lib\subprocess.py", line 607, in check_output
        with Popen(*popenargs, stdout=PIPE, **kwargs) as process:
      File "c:\python34\lib\subprocess.py", line 859, in __init__
        restore_signals, start_new_session)
      File "c:\python34\lib\subprocess.py", line 1114, in _execute_child
        startupinfo)
    OSError: [WinError 193] %1 is not a valid Win32 application

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\ant6\AppData\Local\Temp\pip-gqpn5qkg-build
You are using pip version 7.1.2, however version 8.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

**Comment by antnieszka** [comment]
The same error in cmd.exe

**Comment by grzanka** [comment]
I see, probably Windows cannot execute command `c:\python34\lib\site-packages\..\..\Scripts\versioneer install`
It looks setup.py code needs better error handling.

The solution could be to construct the command to execute to be:
`PATH_TO_PYTHON_INTERPRETER c:\python34\lib\site-packages\..\..\Scripts\versioneer install`
or
`PYTHON_INTERPRETER c:\python34\lib\site-packages\..\..\Scripts\versioneer install`

**Comment by grzanka** [comment]
Blind commit: https://github.com/DataMedSci/beprof/commit/7e75cd274e5d8f66788d95de9b0a0edd0ce46e25

**Comment by grzanka** [comment]
Does it work now ?

**Comment by antnieszka** [comment]
It does :)

```
ant6@DESKTOP-K5I4GEC MINGW64 ~/Downloads
$ pip install git+https://github.com/DataMedSci/beprof.git@feature/42-windows-pip
Collecting git+https://github.com/DataMedSci/beprof.git@feature/42-windows-pip
  Cloning https://github.com/DataMedSci/beprof.git (to feature/42-windows-pip) to c:\users\ant6\appdata\local\temp\pip-etfc6r3g-build
Collecting numpy>=1.10.4 (from beprof==0.post0.dev1611466584617)
  Using cached numpy-1.11.0-cp34-none-win_amd64.whl
Installing collected packages: numpy, beprof
  Running setup.py install for beprof
Successfully installed beprof-0.post0.dev1611466584627 numpy-1.11.0
You are using pip version 7.1.2, however version 8.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

Some "tests":

```
[...]
>>> from beprof import profile
>>> profile.Profile([[1,2], [2, 2], [3,4]])
Profile([[1, 2],
       [2, 2],
       [3, 4]])
```
