### ISSUE TITLE
Make beprof working with numpy 1.8 

### ISSUE THREAD

**Issue by grzanka** [DataMedSci/beprof#33]
Numpy 1.8 is shipped by default in Ubuntu 14.04 LTS, we should support it

**Comment by grzanka** [comment]
Example session with docker image containing Ubuntu 14.04 with few packages installed (check: https://hub.docker.com/r/grzanka/pyqt_ubuntu_testing/~/dockerfile/)

```
# grzanka at gajewski-dell in ~ [14:11:47]
→ docker run --rm -it grzanka/pyqt_ubuntu_testing /bin/bash
test@540b1fde5037:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:    14.04
Codename:   trusty
test@540b1fde5037:~$ pip3 freeze
Pillow==2.3.0
chardet==2.2.1
colorama==0.2.5
decorator==3.4.0
html5lib==0.999
matplotlib==1.3.1
nose==1.3.1
numpy==1.8.2
pydicom==0.9.9
pyparsing==2.0.1
python-dateutil==2.0
pytz==2012c
requests==2.2.1
scipy==0.13.3
six==1.5.2
tornado==3.1.1
urllib3==1.7.1
wheel==0.24.0
test@540b1fde5037:~$ python3 -V
Python 3.4.3
test@540b1fde5037:~$ python3       
Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.version.version
'1.8.2'
>>> import scipy as sp
>>> sp.version.version
'0.13.3'
>>> 
test@540b1fde5037:~$ pip3 install -i https://testpypi.python.org/pypi beprof==0.post0.dev1511465204600 --user
Downloading/unpacking beprof==0.post0.dev1511465204600
  Downloading beprof-0.post0.dev1511465204600-py2.py3-none-any.whl
Downloading/unpacking numpy>=1.10.4 (from beprof==0.post0.dev1511465204600)
  Could not find a version that satisfies the requirement numpy>=1.10.4 (from beprof==0.post0.dev1511465204600) (from versions: 1.9.3, 1.9.3)
  Some externally hosted files were ignored (use --allow-external to allow).
Cleaning up...
No distributions matching the version for numpy>=1.10.4 (from beprof==0.post0.dev1511465204600)
Storing debug log for failure in /home/test/.pip/pip.log
```

**Comment by antnieszka** [comment]
Ok, I downloaded docker ubuntu:14.04, here is my 'short-log':
- apt-get install python python-pip git
- pip install 'numpy==1.8'
- pip install --no-deps git+https://github.com/DataMedSci/beprof.git
```sh
root@d86d0c732e10:/# pip freeze
argparse==1.2.1
beprof==0.post.dev1821480948560
chardet==2.0.1
colorama==0.2.5
html5lib==0.999
numpy==1.8.0
requests==2.2.1
six==1.5.2
urllib3==1.7.1
versioneer==0.17
wheel==0.24.0
wsgiref==0.1.2
```
When I open Python shell and try some imports/creating new beprof objects - everything works fine.
Also pip tried to download new version of numpy:
```sh
root@d86d0c732e10:/# pip install --upgrade numpy
Downloading/unpacking numpy from https://pypi.python.org/packages/16/f5/b432f028134dd30cfbf6f21b8264a9938e5e0f75204e72453af08d67eb0b/numpy-1.11.2.tar.gz#md5=03bd7927c314c43780271bf1ab795ebc
  Downloading numpy-1.11.2.tar.gz (4.2MB): 143kB downloaded
Cleaning up...
Operation cancelled by user
```

**Comment by grzanka** [comment]
Try to get Ubuntu 14.04 and numpy installed via apt. Then install beprof without deps. Check if it is working (by running tests).

**Comment by antnieszka** [comment]
@grzanka server version will do?

**Comment by antnieszka** [comment]
I'm downloading this one `64-bit PC (AMD64) server install image` from http://releases.ubuntu.com/14.04/

**Comment by grzanka** [comment]
Isn't it easier via docker ?

**Comment by antnieszka** [comment]
I did the previous one with `docker pull ubuntu:14.04`... I'm sorry, I thought You meant to get typical Ubuntu iso.

**Comment by grzanka** [comment]
You can get it via docker, but install numpy via apt-get and then beprof via pip in such way it won't automatically suck new numpy

**Comment by antnieszka** [comment]
Ok. I previously did `pip install --no-deps git+https://github.com/DataMedSci/beprof.git` and it ignored numpy dep.

**Comment by antnieszka** [comment]
```
root@73d5354e1a4a:/# apt-get install python-numpy=1.8.0   
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Version '1.8.0' for 'python-numpy' was not found
```

**Comment by grzanka** [comment]
apt-get update && apt-get search numpy

**Comment by grzanka** [comment]
or apt-cache search numpy

**Comment by ant6** [comment]
It is here, but only in newer versions :(
```
root@73d5354e1a4a:/# apt-cache search numpy
python-numpy - Numerical Python adds a fast array facility to the Python language
```

**Comment by antnieszka** [comment]
`apt-get install python-numpy` installed numpy 1.8.2

**Comment by antnieszka** [comment]
```
root@73d5354e1a4a:/# pip install setuptools versioneer
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python2.7/dist-packages
Downloading/unpacking versioneer
  Downloading versioneer-0.17-py2.py3-none-any.whl
Installing collected packages: versioneer
Successfully installed versioneer
Cleaning up...
root@73d5354e1a4a:/# pip install --no-deps git+https://github.com/DataMedSci/beprof.git
Downloading/unpacking git+https://github.com/DataMedSci/beprof.git
  Cloning https://github.com/DataMedSci/beprof.git to /tmp/pip-lsxyJA-build
  Running setup.py (path:/tmp/pip-lsxyJA-build/setup.py) egg_info for package from git+https://github.com/DataMedSci/beprof.git
    
    warning: no previously-included files found matching '.gitkeep'
    warning: no previously-included files found matching '.gitconfig'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files found matching '.travis.yml'
    warning: no previously-included files found matching 'appveyor.yml'
    no previously-included directories found matching '.travis'
    no previously-included directories found matching 'install_deps.sh'
Installing collected packages: beprof
  Running setup.py install for beprof
    UPDATING build/lib.linux-x86_64-2.7/beprof/_version.py
    set build/lib.linux-x86_64-2.7/beprof/_version.py to '0.post.dev182'
    
    warning: no previously-included files found matching '.gitkeep'
    warning: no previously-included files found matching '.gitconfig'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files found matching '.travis.yml'
    warning: no previously-included files found matching 'appveyor.yml'
    no previously-included directories found matching '.travis'
    no previously-included directories found matching 'install_deps.sh'
Successfully installed beprof
Cleaning up...
```
And it seems to work in python shell.

**Comment by grzanka** [comment]
Installation works, great, but what about beprof tests ?

**Comment by antnieszka** [comment]
@grzanka I was away for some time, sorry.
```py
root@73d5354e1a4a:/usr/local/lib/python2.7/dist-packages/beprof# python -m doctest -v functions.py
Trying:
    print(medfilt(np.array([1., 15., 1., 1., 1.]), 3))
Expecting:
    [ 1.  1.  1.  1.  1.]
ok
Trying:
    print(medfilt(np.array([15., 1., 1., 1., 1.]), 3))
Expecting:
    [ 15.   1.   1.   1.   1.]
ok
2 items had no tests:
    functions
    functions.subtract
1 items passed all tests:
   2 tests in functions.medfilt
2 tests in 3 items.
2 passed and 0 failed.
Test passed.
root@73d5354e1a4a:/usr/local/lib/python2.7/dist-packages/beprof# python -m doctest -v curve.py
Trying:
    print(Curve([[0,0], [5, 5], [10, 0]])            .change_domain([1, 2, 8, 9]).y)
Expecting:
    [ 1.  2.  2.  1.]
**********************************************************************
File "curve.py", line 97, in curve.Curve.change_domain
Failed example:
    print(Curve([[0,0], [5, 5], [10, 0]])            .change_domain([1, 2, 8, 9]).y)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest curve.Curve.change_domain[0]>", line 1, in <module>
        print(Curve([[0,0], [5, 5], [10, 0]])            .change_domain([1, 2, 8, 9]).y)
      File "curve.py", line 116, in change_domain
        obj = self.__class__(np.stack((domain, y), axis=1), **self.__dict__['metadata'])
    AttributeError: 'module' object has no attribute 'stack'
Trying:
    Curve([[0, 0], [2, 2], [4, 4]]).evaluate_at_x([1, 2 ,3])
Expecting:
    array([ 1.,  2.,  3.])
ok
Trying:
    Curve([[0, 0], [2, 2], [4, 4]]).evaluate_at_x(            [-1, 1, 2 ,3, 5], 100)
Expecting:
    array([ 100.,    1.,    2.,    3.,  100.])
ok
Trying:
    print(Curve([[0,0], [5, 5], [10, 0]]).rebinned(1, 0).x)
Expecting:
    [  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
**********************************************************************
File "curve.py", line 129, in curve.Curve.rebinned
Failed example:
    print(Curve([[0,0], [5, 5], [10, 0]]).rebinned(1, 0).x)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest curve.Curve.rebinned[0]>", line 1, in <module>
        print(Curve([[0,0], [5, 5], [10, 0]]).rebinned(1, 0).x)
      File "curve.py", line 155, in rebinned
        return self.change_domain(domain)
      File "curve.py", line 116, in change_domain
        obj = self.__class__(np.stack((domain, y), axis=1), **self.__dict__['metadata'])
    AttributeError: 'module' object has no attribute 'stack'
Trying:
    Curve([[0, 0], [1, 1], [2, 2], [3, 1]]).subtract(            Curve([[-1, 1], [5, 1]])) is None
Expecting:
    True
ok
Trying:
    Curve([[0, 0], [1, 1], [2, 2], [3, 1]]).subtract(            Curve([[-1, 1], [5, 1]]), new_obj=True).y
Expecting:
    DataSet([-1.,  0.,  1.,  0.])
**********************************************************************
File "curve.py", line 196, in curve.Curve.subtract
Failed example:
    Curve([[0, 0], [1, 1], [2, 2], [3, 1]]).subtract(            Curve([[-1, 1], [5, 1]]), new_obj=True).y
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest curve.Curve.subtract[1]>", line 1, in <module>
        Curve([[0, 0], [1, 1], [2, 2], [3, 1]]).subtract(            Curve([[-1, 1], [5, 1]]), new_obj=True).y
      File "curve.py", line 226, in subtract
        return functions.subtract(self, curve2.change_domain(self.x))
      File "curve.py", line 116, in change_domain
        obj = self.__class__(np.stack((domain, y), axis=1), **self.__dict__['metadata'])
    AttributeError: 'module' object has no attribute 'stack'
Trying:
    Curve([[0, 0], [1, 1], [2, 2], [3, 1]]).subtract(            Curve([[1, -1], [2, -1]]), new_obj=True) is None
Expecting:
    True
No handlers could be found for logger "curve"
ok
12 items had no tests:
    curve
    curve.Curve
    curve.Curve.__array_finalize__
    curve.Curve.__new__
    curve.Curve.__str__
    curve.Curve.rescale
    curve.Curve.smooth
    curve.Curve.x
    curve.Curve.y
    curve.Curve.y_at_x
    curve.DataSet
    curve.main
1 items passed all tests:
   2 tests in curve.Curve.evaluate_at_x
**********************************************************************
3 items had failures:
   1 of   1 in curve.Curve.change_domain
   1 of   1 in curve.Curve.rebinned
   1 of   3 in curve.Curve.subtract
7 tests in 16 items.
4 passed and 3 failed.
***Test Failed*** 3 failures.
root@73d5354e1a4a:/usr/local/lib/python2.7/dist-packages/beprof# python -m doctest -v profile.py
Trying:
    float(Profile([[0.0, 5.0], [0.1, 10.0], [0.2, 20.0], [0.3, 10.0]])            .x_at_y(5.))
Expecting:
    0.0
**********************************************************************
File "profile.py", line 42, in profile.Profile.x_at_y
Failed example:
    float(Profile([[0.0, 5.0], [0.1, 10.0], [0.2, 20.0], [0.3, 10.0]])            .x_at_y(5.))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest profile.Profile.x_at_y[0]>", line 1, in <module>
        float(Profile([[0.0, 5.0], [0.1, 10.0], [0.2, 20.0], [0.3, 10.0]])            .x_at_y(5.))
      File "profile.py", line 20, in __new__
        new = super().__new__(cls, input_array, **meta)
    TypeError: super() takes at least 1 argument (0 given)
Trying:
    float(Profile([[0.0, 5.0], [0.1, 10.0], [0.2, 20.0], [0.3, 10.0]])            .x_at_y(10.))
Expecting:
    0.1
**********************************************************************
File "profile.py", line 47, in profile.Profile.x_at_y
Failed example:
    float(Profile([[0.0, 5.0], [0.1, 10.0], [0.2, 20.0], [0.3, 10.0]])            .x_at_y(10.))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest profile.Profile.x_at_y[1]>", line 1, in <module>
        float(Profile([[0.0, 5.0], [0.1, 10.0], [0.2, 20.0], [0.3, 10.0]])            .x_at_y(10.))
      File "profile.py", line 20, in __new__
        new = super().__new__(cls, input_array, **meta)
    TypeError: super() takes at least 1 argument (0 given)
Trying:
    float(Profile([[0.0, 5.0], [0.1, 10.0], [0.2, 20.0], [0.3, 10.0]])            .x_at_y(10., reverse=True))
Expecting:
    0.3
**********************************************************************
File "profile.py", line 52, in profile.Profile.x_at_y
Failed example:
    float(Profile([[0.0, 5.0], [0.1, 10.0], [0.2, 20.0], [0.3, 10.0]])            .x_at_y(10., reverse=True))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest profile.Profile.x_at_y[2]>", line 1, in <module>
        float(Profile([[0.0, 5.0], [0.1, 10.0], [0.2, 20.0], [0.3, 10.0]])            .x_at_y(10., reverse=True))
      File "profile.py", line 20, in __new__
        new = super().__new__(cls, input_array, **meta)
    TypeError: super() takes at least 1 argument (0 given)
Trying:
    float(Profile([[0.0, 5.0], [0.1, 10.0], [0.2, 20.0], [0.3, 10.0]])            .x_at_y(7.5))
Expecting:
    0.05
**********************************************************************
File "profile.py", line 56, in profile.Profile.x_at_y
Failed example:
    float(Profile([[0.0, 5.0], [0.1, 10.0], [0.2, 20.0], [0.3, 10.0]])            .x_at_y(7.5))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest profile.Profile.x_at_y[3]>", line 1, in <module>
        float(Profile([[0.0, 5.0], [0.1, 10.0], [0.2, 20.0], [0.3, 10.0]])            .x_at_y(7.5))
      File "profile.py", line 20, in __new__
        new = super().__new__(cls, input_array, **meta)
    TypeError: super() takes at least 1 argument (0 given)
Trying:
    float(Profile([[0.0, 5.0], [0.1, 10.0], [0.2, 20.0], [0.3, 10.0]])            .x_at_y(2.0))
Expecting:
    nan
**********************************************************************
File "profile.py", line 60, in profile.Profile.x_at_y
Failed example:
    float(Profile([[0.0, 5.0], [0.1, 10.0], [0.2, 20.0], [0.3, 10.0]])            .x_at_y(2.0))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest profile.Profile.x_at_y[4]>", line 1, in <module>
        float(Profile([[0.0, 5.0], [0.1, 10.0], [0.2, 20.0], [0.3, 10.0]])            .x_at_y(2.0))
      File "profile.py", line 20, in __new__
        new = super().__new__(cls, input_array, **meta)
    TypeError: super() takes at least 1 argument (0 given)
Trying:
    float(Profile([[0.0, 5.0], [0.1, 10.0], [0.2, 20.0], [0.3, 10.0]])            .x_at_y(22.0))
Expecting:
    nan
**********************************************************************
File "profile.py", line 64, in profile.Profile.x_at_y
Failed example:
    float(Profile([[0.0, 5.0], [0.1, 10.0], [0.2, 20.0], [0.3, 10.0]])            .x_at_y(22.0))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest profile.Profile.x_at_y[5]>", line 1, in <module>
        float(Profile([[0.0, 5.0], [0.1, 10.0], [0.2, 20.0], [0.3, 10.0]])            .x_at_y(22.0))
      File "profile.py", line 20, in __new__
        new = super().__new__(cls, input_array, **meta)
    TypeError: super() takes at least 1 argument (0 given)
9 items had no tests:
    profile
    profile.Profile
    profile.Profile.__array_finalize__
    profile.Profile.__new__
    profile.Profile.__str__
    profile.Profile.fwhm
    profile.Profile.normalize
    profile.Profile.width
    profile.main
**********************************************************************
1 items had failures:
   6 of   6 in profile.Profile.x_at_y
6 tests in 10 items.
0 passed and 6 failed.
***Test Failed*** 6 failures.
```
Python 2.7 doctests fail... but only some errors may be caused by numpy e.g.
```py
File "curve.py", line 116, in change_domain
        obj = self.__class__(np.stack((domain, y), axis=1), **self.__dict__['metadata'])
    AttributeError: 'module' object has no attribute 'stack'
```
Something is still wrong with logger, there is also a issue with `super()` but i probably have it covered in #99 on branch https://github.com/ant6/beprof/commit/648cc96191d62a49fa7cc0c00cdd43dd905cab2a

**Comment by grzanka** [comment]
Check in which numpy version `np.stack` was introduced. Maybe it can replaced with something other.

**Comment by antnieszka** [comment]
https://github.com/numpy/numpy/blob/v1.11.0/numpy/core/shape_base.py#L282-L350
1.10

http://stackoverflow.com/questions/35517954/numpy-module-object-has-no-attribute-stack -> so we can just 'take' it from numpy code, but I don't know if this is a good idea :/

**Comment by grzanka** [comment]
Bad idea. Start with getting understanding.

Do you know what `np.stack` is doing ?
Check 1.8.1 user guide and find a method doing similar job: https://docs.scipy.org/doc/numpy-1.8.1/user/index.html

**Comment by antnieszka** [comment]
I remember it was something with `hstack`, `dstack` and `vstack` - those https://docs.scipy.org/doc/numpy-1.8.1/reference/routines.array-manipulation.html#joining-arrays in general appeared earlier in code, and they exist in numpy 1.8. Maybe we could use them and possibly solve the issue?

**Comment by grzanka** [comment]
Good idea, but start with understanding first.

**Comment by ant6** [comment]
I think `stack(arrays, axis=1)` should do the same as `np.concatenate(arrays, axis=1)` or `hstack(arrays)`.

**Comment by antnieszka** [comment]
```py
>>> a = np.array((1,2,3))
>>> b = np.array((4,5,6))
>>> np.stack((a,b), axis=1) == np.dstack((a,b))
array([[[ True,  True],
        [ True,  True],
        [ True,  True]]], dtype=bool)
```

**Comment by antnieszka** [comment]
Another thing (there are no unit_tests after such installation):

```sh
root@73d5354e1a4a:~# updatedb
root@73d5354e1a4a:~# locate curve.py
/usr/local/lib/python2.7/dist-packages/beprof/curve.py
/usr/local/lib/python2.7/dist-packages/beprof/curve.pyc
root@73d5354e1a4a:~# locate profile.py
/usr/lib/python2.7/profile.py
/usr/lib/python2.7/profile.pyc
/usr/lib/python3.4/profile.py
/usr/local/lib/python2.7/dist-packages/beprof/profile.py
/usr/local/lib/python2.7/dist-packages/beprof/profile.pyc
root@73d5354e1a4a:~# locate test_profile.py
root@73d5354e1a4a:~# locate test_curve.py
root@73d5354e1a4a:~# 
```

**Comment by antnieszka** [comment]
And I looked into beprof*.whl generated locally and there were no test either :(

**Comment by antnieszka** [comment]
Maybe we should package tests with `data_files` https://docs.python.org/2/distutils/setupscript.html#installing-additional-files ?

**Comment by grzanka** [comment]
dstack looks OK. 

Speaking of tests inclusion - make a separate issue on that and check first how other maintainers of big packages are doing that.

**Comment by antnieszka** [comment]
Ok, sure. As for `super()` calls I'll download source code from my other branch and check if it still appears.

**Comment by antnieszka** [comment]
@grzanka after downloading version from #99 (I mean exactly this commit https://github.com/ant6/beprof/commit/3df19431b8a365a6ad5161ec7a0e94d080d0f466) all doctests in profile.py pass. Only curve.py fails (logger and call to `stack` as in logs above).

**Comment by grzanka** [comment]
Great, time to make a PR

**Comment by antnieszka** [comment]
@grzanka It's mixed with tests - can I make one bigger PR with some new tests, `stack`->`dstack` and fixed `super()` call?

**Comment by grzanka** [comment]
sure

**Comment by antnieszka** [comment]
Ok, by the way... solution with `dstack` works but... we have to extract it (its nested into additional list :/) So call like this works:
`    obj = curve1.__class__(np.dstack((coord1, coord2))[0], **curve1.__dict__['metadata'])`
but this one does not:
`    obj = curve1.__class__(np.dstack((coord1, coord2)), **curve1.__dict__['metadata'])`

**Comment by grzanka** [comment]
as long as you drop a line of comment explaining the code - why not ?
