### ISSUE TITLE
Setup.py develop fails

### ISSUE THREAD

**Issue by antnieszka** [DataMedSci/beprof#41]
```
(beprof) {11:56} ~/Downloads/beprof@master ant6% ➜ python setup.py develop
/usr/lib64/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'develop'
```

**Comment by grzanka** [comment]
Is is still valid ? If yes, please tell more about OS and python version.

**Comment by antnieszka** [comment]
OpenSuse 42.1 Leap with Python 3.4. I'll try to rerun this.

In the meantime on Xubuntu 16.04 VirtualBox machine:

```
ant6@ant6-VBXU:~/Downloads/beprof-master$ python setup.py develop
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
    stream.write(fs % msg)
TypeError: unicode argument expected, got 'str'
Logged from file show.py, line 127
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
    stream.write(fs % msg)
TypeError: unicode argument expected, got 'str'
Logged from file show.py, line 128
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
    stream.write(fs % msg)
TypeError: unicode argument expected, got 'str'
Logged from file show.py, line 129
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
    stream.write(fs % msg)
TypeError: unicode argument expected, got 'str'
Logged from file show.py, line 130
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
    stream.write(fs % msg)
TypeError: unicode argument expected, got 'str'
Logged from file show.py, line 131
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
    stream.write(fs % msg)
TypeError: unicode argument expected, got 'str'
Logged from file show.py, line 132
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
    stream.write(fs % msg)
TypeError: unicode argument expected, got 'str'
Logged from file show.py, line 133
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
    stream.write(fs % msg)
TypeError: unicode argument expected, got 'str'
Logged from file show.py, line 134
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
    stream.write(fs % msg)
TypeError: unicode argument expected, got 'str'
Logged from file show.py, line 136
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
    stream.write(fs % msg)
TypeError: unicode argument expected, got 'str'
Logged from file show.py, line 137
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
    stream.write(fs % msg)
TypeError: unicode argument expected, got 'str'
Logged from file show.py, line 138
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
    stream.write(fs % msg)
TypeError: unicode argument expected, got 'str'
Logged from file show.py, line 139
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
    stream.write(fs % msg)
TypeError: unicode argument expected, got 'str'
Logged from file show.py, line 140
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
    stream.write(fs % msg)
TypeError: unicode argument expected, got 'str'
Logged from file show.py, line 142
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
    stream.write(fs % msg)
TypeError: unicode argument expected, got 'str'
Logged from file show.py, line 142
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
    stream.write(fs % msg)
TypeError: unicode argument expected, got 'str'
Logged from file show.py, line 142
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
    stream.write(fs % msg)
TypeError: unicode argument expected, got 'str'
Logged from file show.py, line 142
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
    stream.write(fs % msg)
TypeError: unicode argument expected, got 'str'
Logged from file show.py, line 142
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
    stream.write(fs % msg)
TypeError: unicode argument expected, got 'str'
Logged from file show.py, line 142
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
    stream.write(fs % msg)
TypeError: unicode argument expected, got 'str'
Logged from file show.py, line 142
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
    stream.write(fs % msg)
TypeError: unicode argument expected, got 'str'
Logged from file show.py, line 142
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
    stream.write(fs % msg)
TypeError: unicode argument expected, got 'str'
Logged from file show.py, line 144
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
    stream.write(fs % msg)
TypeError: unicode argument expected, got 'str'
Logged from file show.py, line 147
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
    stream.write(fs % msg)
TypeError: unicode argument expected, got 'str'
Logged from file show.py, line 147
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
    stream.write(fs % msg)
TypeError: unicode argument expected, got 'str'
Logged from file show.py, line 147
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
    stream.write(fs % msg)
TypeError: unicode argument expected, got 'str'
Logged from file show.py, line 147
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
    stream.write(fs % msg)
TypeError: unicode argument expected, got 'str'
Logged from file show.py, line 147
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
    stream.write(fs % msg)
TypeError: unicode argument expected, got 'str'
Logged from file show.py, line 147
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
    stream.write(fs % msg)
TypeError: unicode argument expected, got 'str'
Logged from file show.py, line 147
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
    stream.write(fs % msg)
TypeError: unicode argument expected, got 'str'
Logged from file show.py, line 147
Traceback (most recent call last):
  File "setup.py", line 84, in <module>
    version=get_version(),
  File "setup.py", line 61, in get_version
    setup_versioneer()
  File "setup.py", line 40, in setup_versioneer
    if x.startswith("Location")][0]
IndexError: list index out of range
```

**Comment by grzanka** [comment]
Clean Docker 16.04 Ubuntu:

```
root@87271b770cb8:~# git clone https://github.com/DataMedSci/beprof.git
Cloning into 'beprof'...
remote: Counting objects: 622, done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 622 (delta 12), reused 0 (delta 0), pack-reused 593
Receiving objects: 100% (622/622), 151.97 KiB | 0 bytes/s, done.
Resolving deltas: 100% (339/339), done.
Checking connectivity... done.
root@87271b770cb8:~# cd beprof/
root@87271b770cb8:~/beprof# python setup.py develop  
/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py:187: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. This is a legacy behavior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of versions, sort the Version instances directly. If you have another use case requiring the tuple, please file a bug with the setuptools project describing that need.
  stacklevel=1,
/usr/local/lib/python2.7/dist-packages/setuptools/dist.py:285: UserWarning: Normalizing '0.post.dev1561466021093' to '0.post0.dev1561466021093'
  normalized_version,
running develop
running egg_info
creating beprof.egg-info
writing requirements to beprof.egg-info/requires.txt
writing beprof.egg-info/PKG-INFO
writing top-level names to beprof.egg-info/top_level.txt
writing dependency_links to beprof.egg-info/dependency_links.txt
writing manifest file 'beprof.egg-info/SOURCES.txt'
reading manifest file 'beprof.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching '.gitkeep'
warning: no previously-included files found matching '.gitconfig'
warning: no previously-included files found matching 'tox.ini'
warning: no previously-included files found matching '.travis.yml'
warning: no previously-included files found matching 'appveyor.yml'
no previously-included directories found matching '.travis'
no previously-included directories found matching 'install_deps.sh'
writing manifest file 'beprof.egg-info/SOURCES.txt'
running build_ext
Creating /usr/local/lib/python2.7/dist-packages/beprof.egg-link (link to .)
Adding beprof 0.post0.dev1561466021093 to easy-install.pth file

Installed /root/beprof
Processing dependencies for beprof==0.post0.dev1561466021093
Searching for scipy==0.17.0
Best match: scipy 0.17.0
Adding scipy 0.17.0 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Searching for numpy==1.11.0
Best match: numpy 1.11.0
Adding numpy 1.11.0 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Finished processing dependencies for beprof==0.post0.dev1561466021093
root@87271b770cb8:~/beprof# 
```

**Comment by antnieszka** [comment]
Recent run on an academy server:
Python 2.7.5,

```
~/beprof master ± python setup.py develop
You are using pip version 7.1.2, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Traceback (most recent call last):
  File "setup.py", line 116, in <module>
    version=get_version(),
  File "setup.py", line 89, in get_version
    setup_versioneer()
  File "setup.py", line 56, in setup_versioneer
    if x.startswith("Location")][0]
IndexError: list index out of range
```

This again :/

```
~/beprof master 10s ± python3 setup.py develop
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    import setuptools
ImportError: No module named 'setuptools'
```

This is for developers and virtenv usually installs setuptools, so should we add it to requirements or https://github.com/DataMedSci/beprof/blob/master/CONTRIBUTING.rst#get-started ?

**Comment by antnieszka** [comment]
On the other hand - it worked on windows10 with Python 3.4:

```
ant6@DESKTOP-K5I4GEC MINGW64 ~/Downloads/beprof-master/beprof-master
$ python setup.py develop
C:\Python34\lib\site-packages\pkg_resources\__init__.py:203: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. This is a legacy behavior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of versions, sort the Version instances directly. If you have another use case requiring the tuple, please file a bug with the setuptools project describing that need.
  stacklevel=1,
running develop
running egg_info
creating beprof.egg-info
writing top-level names to beprof.egg-info\top_level.txt
writing beprof.egg-info\PKG-INFO
writing dependency_links to beprof.egg-info\dependency_links.txt
writing requirements to beprof.egg-info\requires.txt
writing manifest file 'beprof.egg-info\SOURCES.txt'
reading manifest file 'beprof.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching '.gitkeep'
warning: no previously-included files found matching '.gitconfig'
warning: no previously-included files found matching 'tox.ini'
warning: no previously-included files found matching '.travis.yml'
warning: no previously-included files found matching 'appveyor.yml'
no previously-included directories found matching '.travis'
no previously-included directories found matching 'install_deps.sh'
writing manifest file 'beprof.egg-info\SOURCES.txt'
running build_ext
Creating c:\python34\lib\site-packages\beprof.egg-link (link to .)
Adding beprof 0+unknown to easy-install.pth file

Installed c:\users\ant6\downloads\beprof-master\beprof-master
Processing dependencies for beprof==0+unknown
Searching for numpy==1.11.0
Best match: numpy 1.11.0
Adding numpy 1.11.0 to easy-install.pth file

Using c:\python34\lib\site-packages
Finished processing dependencies for beprof==0+unknown
```

**Comment by ant6** [comment]
By readme i meant https://github.com/DataMedSci/beprof/blob/master/CONTRIBUTING.rst#get-started

**Comment by antnieszka** [comment]
OpenSUSE Leap 42.1, Python 2.7.9:

```
{16-07-02 18:41} ~/Downloads ant6% ➜ git clone https://github.com/DataMedSci/beprof.git
Cloning into 'beprof'...
remote: Counting objects: 626, done.
remote: Total 626 (delta 0), reused 0 (delta 0), pack-reused 626
Receiving objects: 100% (626/626), 152.23 KiB | 170.00 KiB/s, done.
Resolving deltas: 100% (347/347), done.
Checking connectivity... done.
{16-07-02 18:41} ~/Downloads ant6% ➜ cd beprof 
{16-07-02 18:41} ~/Downloads/beprof@master ant6% ➜ ls
appveyor.yml  CONTRIBUTING.rst  LICENSE      requirements.txt  tests
AUTHORS.rst   docs              MANIFEST.in  setup.cfg         tox.ini
beprof        install_deps.sh   README.rst   setup.py          wercker.yml
{16-07-02 18:41} ~/Downloads/beprof@master ant6% ➜ mkvirtualenv beprof         
New python executable in beprof/bin/python
Installing setuptools, pip, wheel...done.
Overwriting beprof/bin/activate with new content
Overwriting beprof/bin/activate.fish with new content
Overwriting beprof/bin/activate.csh with new content
(beprof){16-07-02 18:42} ~/Downloads/beprof@master ant6% ➜ workon beprof 
(beprof){16-07-02 18:42} ~/Downloads/beprof@master ant6% ➜ python --version
Python 2.7.9
(beprof){16-07-02 18:42} ~/Downloads/beprof@master ant6% ➜ pip freeze
wheel==0.24.0
You are using pip version 7.1.2, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(beprof){16-07-02 18:42} ~/Downloads/beprof@master ant6% ➜ python setup.py develop
You are using pip version 7.1.2, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Traceback (most recent call last):
  File "setup.py", line 116, in <module>
    version=get_version(),
  File "setup.py", line 89, in get_version
    setup_versioneer()
  File "setup.py", line 56, in setup_versioneer
    if x.startswith("Location")][0]
IndexError: list index out of range
```

**Comment by antnieszka** [comment]
Another shot, OpenSUSE Leap 42.1, Python 3.4.1:

```
{16-07-02 18:44} ~/Downloads/beprof@master ant6% ➜ mkvirtualenv beprof3 -p /usr/bin/python3
Running virtualenv with interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in beprof3/bin/python3
Also creating executable in beprof3/bin/python
Installing setuptools, pip, wheel...done.
(beprof3){16-07-02 18:44} ~/Downloads/beprof@master ant6% ➜ pip freeze
wheel==0.24.0
You are using pip version 7.1.2, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(beprof3){16-07-02 18:44} ~/Downloads/beprof@master ant6% ➜ ls     
appveyor.yml  CONTRIBUTING.rst  LICENSE      requirements.txt  tests
AUTHORS.rst   docs              MANIFEST.in  setup.cfg         tox.ini
beprof        install_deps.sh   README.rst   setup.py          wercker.yml
(beprof3){16-07-02 18:46} ~/Downloads/beprof@master ant6% ➜ python --version
Python 3.4.1
(beprof3){16-07-02 18:46} ~/Downloads/beprof@master ant6% ➜ python setup.py develop
You are using pip version 7.1.2, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Traceback (most recent call last):
  File "setup.py", line 32, in setup_versioneer
    import versioneer
ImportError: No module named 'versioneer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 41, in setup_versioneer
    subprocess.check_output(["versioneer", "install"])
  File "/usr/lib64/python3.4/subprocess.py", line 607, in check_output
    with Popen(*popenargs, stdout=PIPE, **kwargs) as process:
  File "/usr/lib64/python3.4/subprocess.py", line 858, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.4/subprocess.py", line 1456, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'versioneer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 116, in <module>
    version=get_version(),
  File "setup.py", line 89, in get_version
    setup_versioneer()
  File "setup.py", line 56, in setup_versioneer
    if x.startswith("Location")][0]
IndexError: list index out of range
```

**Comment by antnieszka** [comment]
This log is long, so I just created a gist: https://gist.github.com/ant6/3074ed92d62b7756b6e6f85a2c961e3f
I think installing versioneer and python-devel in linux-case could fix this. I'll try.

**Comment by antnieszka** [comment]
It worked. python-devel|python-dev or python3-devel|python3-dev and versioneer installation is required.

**Comment by antnieszka** [comment]
Installation log: https://gist.github.com/ant6/e701991e47910616b6ea5548ceca1493

**Comment by grzanka** [comment]
I agree - versioneer is needed. What if instead of installing python*dev (which requires root access) user will install setuptools (root access not needed, because pip has nice --user option) ?
Does the problem exists in such situation ?

**Comment by grzanka** [comment]
You are right, it looks that python*dev is needed. I've tried running "python setup.py develop --user" on machine without root access and it complains.

**Comment by grzanka** [comment]
Could you expand documentation in CONTRIBUTING.rst by adding neccesary information ?

**Comment by antnieszka** [comment]
Consider it done.
