### ISSUE TITLE
Pip install from git fails

### ISSUE THREAD

**Issue by antnieszka** [DataMedSci/beprof#42]
```
ant6% ➜ pip install git+https://github.com/grzanka/beprof.git@master 
Collecting git+https://github.com/grzanka/beprof.git@master
  Cloning https://github.com/grzanka/beprof.git (to master) to /tmp/pip-aghy__07-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/tmp/pip-aghy__07-build/setup.py", line 4, in <module>
        import versioneer
    ImportError: No module named 'versioneer'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-aghy__07-build/setup.py", line 9, in <module>
        subprocess.call(["versioneer", "install"])
      File "/usr/lib64/python3.4/subprocess.py", line 537, in call
        with Popen(*popenargs, **kwargs) as p:
      File "/usr/lib64/python3.4/subprocess.py", line 858, in __init__
        restore_signals, start_new_session)
      File "/usr/lib64/python3.4/subprocess.py", line 1456, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    FileNotFoundError: [Errno 2] No such file or directory: 'versioneer'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-aghy__07-build/
```

**Comment by grzanka** [comment]
This can be solved by improving setup.py to have following logic:
1. if versioneer.py file is present (was previously generated), then import it, version can be easily calculated
2. (probably we can skip it) if versioneer.py is absent and pip module versioneer is installed (how to check it?) then generate versioneer.py file (using subprocess.call or some smarter method)
3. if none of abovementioned holds, assume that version cannot be easily calculated and set it manually to 0+unknown. Make sure that also cmdclass works properly in this case.

**Comment by grzanka** [comment]
Remember to make this change also in https://github.com/grzanka/cookiecutter-pip-docker-versioneer

**Comment by grzanka** [comment]
Seems to be fixed in PR #60

**Comment by grzanka** [comment]
@ant6 have you tried if it works ?

**Comment by antnieszka** [comment]
@grzanka I did it now on a clean Ubuntu machine. Just with python-pip and git installed. This is the output:

```
ant6@ant6-VBXU:~$ pip install git+https://github.com/grzanka/beprof.git@master
Collecting git+https://github.com/grzanka/beprof.git@master
  Cloning https://github.com/grzanka/beprof.git (to master) to /tmp/pip-sxCDig-build
    Complete output from command python setup.py egg_info:
    You are using pip version 8.1.1, however version 8.1.2 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-sxCDig-build/setup.py", line 84, in <module>
        version=get_version(),
      File "/tmp/pip-sxCDig-build/setup.py", line 61, in get_version
        setup_versioneer()
      File "/tmp/pip-sxCDig-build/setup.py", line 40, in setup_versioneer
        if x.startswith("Location")][0]
    IndexError: list index out of range

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-sxCDig-build/
```

Looks like another bug, I think.

**Comment by grzanka** [comment]
Have you installed versioneer first, as the instruction says ?

**Comment by antnieszka** [comment]
No, forgot. But still not working:

```
ant6@ant6-VBXU:~$ pip install versioneer
Collecting versioneer
  Downloading versioneer-0.16-py2.py3-none-any.whl
Installing collected packages: versioneer
Successfully installed versioneer
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
ant6@ant6-VBXU:~$ pip install git+https://github.com/grzanka/beprof.git@master
Collecting git+https://github.com/grzanka/beprof.git@master
  Cloning https://github.com/grzanka/beprof.git (to master) to /tmp/pip-cb3VfB-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 127
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 128
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 129
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 130
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 131
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 132
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 133
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 134
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 136
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 137
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 138
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 139
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 140
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 142
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 142
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 142
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 142
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 142
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 142
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 142
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 142
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 144
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 147
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 147
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 147
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 147
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 147
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 147
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 147
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 147
    You are using pip version 8.1.1, however version 8.1.2 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-cb3VfB-build/setup.py", line 84, in <module>
        version=get_version(),
      File "/tmp/pip-cb3VfB-build/setup.py", line 61, in get_version
        setup_versioneer()
      File "/tmp/pip-cb3VfB-build/setup.py", line 40, in setup_versioneer
        if x.startswith("Location")][0]
    IndexError: list index out of range

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-cb3VfB-build/
```

**Comment by antnieszka** [comment]
And that is simply the same error, but longer log. I don't even know why so.

**Comment by grzanka** [comment]
Can you provide more information about Ubuntu and python version ?

**Comment by grzanka** [comment]
Was it docker ?

**Comment by antnieszka** [comment]
Fresh virtual machine with Xubuntu 16.04:

```
ant6@ant6-VBXU:~$ uname -a
Linux ant6-VBXU 4.4.0-22-generic #40-Ubuntu SMP Thu May 12 22:03:46 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
ant6@ant6-VBXU:~$ python --version
Python 2.7.11+
ant6@ant6-VBXU:~$ pip --version
pip 8.1.1 from /usr/lib/python2.7/dist-packages (python 2.7)
ant6@ant6-VBXU:~$ pip freeze
defusedxml==0.4.1
Magic-file-extensions==0.2
pyliblzma==0.5.3
SOAPpy==0.12.22
versioneer==0.16
wstools==0.4.3
```

**Comment by antnieszka** [comment]
No, VirtualBox machine on Windows 10 host.

**Comment by grzanka** [comment]
Can you create new issue with details ? I'll fix it later.
With python3 it works on 14.04

**Comment by antnieszka** [comment]
I'll, closing this one.
