### ISSUE TITLE
Pip install from git fails on (X)Ubuntu 16.04

### ISSUE THREAD

**Issue by antnieszka** [DataMedSci/beprof#69]
The output:

```
ant6@ant6-VBXU:~$ pip install versioneer
Collecting versioneer
  Downloading versioneer-0.16-py2.py3-none-any.whl
Installing collected packages: versioneer
Successfully installed versioneer
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
ant6@ant6-VBXU:~$ pip install git+https://github.com/grzanka/beprof.git@master
Collecting git+https://github.com/grzanka/beprof.git@master
  Cloning https://github.com/grzanka/beprof.git (to master) to /tmp/pip-cb3VfB-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 127
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 128
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 129
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 130
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 131
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 132
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 133
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 134
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 136
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 137
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 138
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 139
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 140
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 142
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 142
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 142
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 142
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 142
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 142
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 142
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 142
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 144
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 147
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 147
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 147
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 147
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 147
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 147
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 147
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 147
    You are using pip version 8.1.1, however version 8.1.2 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-cb3VfB-build/setup.py", line 84, in <module>
        version=get_version(),
      File "/tmp/pip-cb3VfB-build/setup.py", line 61, in get_version
        setup_versioneer()
      File "/tmp/pip-cb3VfB-build/setup.py", line 40, in setup_versioneer
        if x.startswith("Location")][0]
    IndexError: list index out of range

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-cb3VfB-build/
```

and system info:

```
ant6@ant6-VBXU:~$ uname -a
Linux ant6-VBXU 4.4.0-22-generic #40-Ubuntu SMP Thu May 12 22:03:46 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
ant6@ant6-VBXU:~$ python --version
Python 2.7.11+
ant6@ant6-VBXU:~$ pip --version
pip 8.1.1 from /usr/lib/python2.7/dist-packages (python 2.7)
ant6@ant6-VBXU:~$ pip freeze
defusedxml==0.4.1
Magic-file-extensions==0.2
pyliblzma==0.5.3
SOAPpy==0.12.22
versioneer==0.16
wstools==0.4.3
```

Xubuntu 16.04 VirtualBox machine running on Windows 10 host.

**Comment by grzanka** [comment]
For me it works.

Just one thing is missing: setuptools have to be installed.

```
→ docker run --rm -it ubuntu:16.04
root@87271b770cb8:/# apt-get update -qq 
root@87271b770cb8:/# apt-get install -qq -y --no-install-recommends python-pip python-numpy python-scipy git vim >/dev/null
debconf: delaying package configuration, since apt-utils is not installed
root@87271b770cb8:/# python -V
Python 2.7.11+
root@87271b770cb8:/# pip install versioneer
Collecting versioneer
  Downloading versioneer-0.16-py2.py3-none-any.whl
Installing collected packages: versioneer
Successfully installed versioneer-0.16
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
root@87271b770cb8:/# python -c "import numpy as np;print(np.version.version)"
1.11.0
root@87271b770cb8:/# python -c "import scipy as sp;print(sp.version.version)"
0.17.0
root@87271b770cb8:/# uname -a
Linux 87271b770cb8 3.10.0-327.18.2.el7.x86_64 #1 SMP Thu May 12 11:03:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
root@87271b770cb8:/# pip install git+https://github.com/DataMedSci/beprof.git
Collecting git+https://github.com/DataMedSci/beprof.git
  Cloning https://github.com/DataMedSci/beprof.git to /tmp/pip-xZ3dt2-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named setuptools

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-xZ3dt2-build/
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
root@87271b770cb8:/# pip install setuptools
Collecting setuptools
  Downloading setuptools-23.0.0-py2.py3-none-any.whl (435kB)
    100% |################################| 440kB 1.6MB/s 
Installing collected packages: setuptools
Successfully installed setuptools-23.0.0
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
root@87271b770cb8:/# pip install git+https://github.com/DataMedSci/beprof.git
Collecting git+https://github.com/DataMedSci/beprof.git
  Cloning https://github.com/DataMedSci/beprof.git to /tmp/pip-2hXZHz-build
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.10.4 in /usr/lib/python2.7/dist-packages (from beprof===0.post0.dev1561466020742)
Requirement already satisfied (use --upgrade to upgrade): scipy>=0.16.0 in /usr/lib/python2.7/dist-packages (from beprof===0.post0.dev1561466020742)
Installing collected packages: beprof
  Running setup.py install for beprof ... done
Successfully installed beprof-0.post0.dev1561466020743
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by grzanka** [comment]
Your command is wrong:

```
pip install git+https://github.com/grzanka/beprof.git@master
```

DataMedSci not grzanka !

Adding `@master` is also not needed

**Comment by antnieszka** [comment]
`$ pip install git+https://github.com/DataMedSci/beprof.git`
But till fails. I had setuptools installed. Now I even upgraded them and still no results.

```
[...]
      setup_versioneer()
      File "/tmp/pip-0WGJSj-build/setup.py", line 40, in setup_versioneer
        if x.startswith("Location")][0]
    IndexError: list index out of range
```

**Comment by grzanka** [comment]
Try to issue command: `pip show -f versioneer` and send me the results.

**Comment by grzanka** [comment]
It looks the problem is somewhere between lines 36 and 43 of setup.py, where I am trying to extract absolute location of `versioneer` executable installed from versioneer package.

**Comment by antnieszka** [comment]
```
ant6@ant6-VBXU:~$ pip show -f versioneer
---
Metadata-Version: 2.0
Name: versioneer
Version: 0.16
Summary: Easy VCS-based management of project version strings
Home-page: https://github.com/warner/python-versioneer
Author: Brian Warner
Author-email: warner-versioneer@lothar.com
Installer: pip
License: public domain
Location: /home/ant6/.local/lib/python2.7/site-packages
Requires: 
Classifiers:
  Programming Language :: Python
  Programming Language :: Python :: 2
  Programming Language :: Python :: 2.6
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.2
  Programming Language :: Python :: 3.3
  Programming Language :: Python :: 3.4
Files:
  ../../../bin/versioneer
  versioneer-0.16.dist-info/DESCRIPTION.rst
  versioneer-0.16.dist-info/INSTALLER
  versioneer-0.16.dist-info/METADATA
  versioneer-0.16.dist-info/RECORD
  versioneer-0.16.dist-info/WHEEL
  versioneer-0.16.dist-info/metadata.json
  versioneer-0.16.dist-info/top_level.txt
```

**Comment by grzanka** [comment]
Looks OK. Then probably something in your enviroment seems to be the reason of the problem.
Two advices:
- try to set LANG=C and LC_ALL=C (i.e. `export LANG=C`) and try again
- create new, clean Virtual Machine with XUbuntu, install there only necessary packages and check if if problem exists

**Comment by antnieszka** [comment]
```
ant6@ant6-VBXU:~$ export LANG=C
ant6@ant6-VBXU:~$ export LC_ALL=C
ant6@ant6-VBXU:~$ pip install git+https://github.com/DataMedSci/beprof.git
Collecting git+https://github.com/DataMedSci/beprof.git
  Cloning https://github.com/DataMedSci/beprof.git to /tmp/pip-HCPfTg-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 127
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 128
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 129
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 130
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 131
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 132
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 133
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 134
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 136
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 137
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 138
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 139
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 140
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 142
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 142
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 142
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 142
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 142
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 142
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 142
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 142
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 144
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 147
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 147
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 147
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 147
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 147
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 147
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 147
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 147
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-HCPfTg-build/setup.py", line 84, in <module>
        version=get_version(),
      File "/tmp/pip-HCPfTg-build/setup.py", line 61, in get_version
        setup_versioneer()
      File "/tmp/pip-HCPfTg-build/setup.py", line 40, in setup_versioneer
        if x.startswith("Location")][0]
    IndexError: list index out of range

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-HCPfTg-build/
```

**Comment by grzanka** [comment]
If you want to debug it yourself, following might help:
1. Go into problematic VM and clone beprof repo locally
2. Use following method to install via pip from **local** git repository:

```
import pip
pip.main(["install","git+file:///Users/grzanka/PycharmProjects/beprof/.git","--user"])
```

it is equivalent to

```
pip install git+file:///Users/grzanka/PycharmProjects/beprof/.git --user
```

First one has the advantage that you can put it in python script and run via Pycharm debugger to spot the problem (use step-by-step execution and breakpoints). You need to replace path to the repo of course.

Remember that each time you change some file, do following steps:
1. Uninstall beprof (pip uninstall beprof). Even if installation failed there might be some trash.
2. Commit local changes. Pip is getting files from GIT repo, not local workspace.

**Comment by antnieszka** [comment]
Clean, new xubuntu VM - here is what I did:
- try pip `install git+https://github.com/DataMedSci/beprof.git`
- oops, no pip - run `apt-get install python-pip`
- try again... no git
- `apt-get install git`

```
~$ pip install git+https://github.com/DataMedSci/beprof.gitCollecting git+https://github.com/DataMedSci/beprof.git
  Cloning https://github.com/DataMedSci/beprof.git to /tmp/pip-eiimco-build
    Complete output from command python setup.py egg_info:
    You are using pip version 8.1.1, however version 8.1.2 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-eiimco-build/setup.py", line 116, in <module>
        version=get_version(),
      File "/tmp/pip-eiimco-build/setup.py", line 89, in get_version
        setup_versioneer()
      File "/tmp/pip-eiimco-build/setup.py", line 56, in setup_versioneer
        if x.startswith("Location")][0]
    IndexError: list index out of range
```
- go look at readme...
- run `pip install setuptools versioneer`
- result: `Successfully installed setuptools-20.7.0 versioneer`
- re-run `pip install git+...`
- aaaaand, again (this time the longer verion from my first comment):

```
[...]
      File "/tmp/pip-8IhNPr-build/setup.py", line 56, in setup_versioneer
        if x.startswith("Location")][0]
    IndexError: list index out of range
```

Then I ran:
- `git clone https://github.com/DataMedSci/beprof.git`
- `cd beprof`
- inside `python`:

```
>>> import pip
>>> pip.main(["install","git+file:/home/ant6/Downloads/beprof/.git","--user"])

[...]
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 147
    Traceback (most recent call last):
      File "/usr/lib/python2.7/logging/__init__.py", line 882, in emit
        stream.write(fs % msg)
    TypeError: unicode argument expected, got 'str'
    Logged from file show.py, line 147
    You are using pip version 8.1.1, however version 8.1.2 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-HFXEMu-build/setup.py", line 116, in <module>
        version=get_version(),
      File "/tmp/pip-HFXEMu-build/setup.py", line 89, in get_version
        setup_versioneer()
      File "/tmp/pip-HFXEMu-build/setup.py", line 56, in setup_versioneer
        if x.startswith("Location")][0]
```

this fails too:

```
~/Downloads/beprof$ export LANG=C
~/Downloads/beprof$ export LC_ALL=C
~/Downloads/beprof$ pip install git+file:/home/ant6/Downloads/beprof/.git --user
```

There is 225MB of updates... should I just donwload them and try?...

Working git directory clean and:

```
$ pip uninstall beprof
Cannot uninstall requirement beprof, not installed
```

**Comment by antnieszka** [comment]
I installed VB Addons to use clipboard and such and nothing more then above.

**Comment by antnieszka** [comment]
It seems it is just VM related issue. I just installed Xubuntu on my computer using the same .iso file which I used for both VirtualBox VMs. It works. I think we can close this issue, no one usually uses VMs for development with VB Addons :P Or create minor issue to investigate in the future. Far future.

**Comment by antnieszka** [comment]
After installation via pip install git+https:...

```
{16-06-25 1:38} ~/Downloads ant6% ➜ pip uninstall beprof                                           
Uninstalling beprof-0.post0.dev1671466811317:
  /home/ant6/.local/lib/python2.7/site-packages/beprof-0.post0.dev1671466811317.egg-info
  /home/ant6/.local/lib/python2.7/site-packages/beprof/__init__.py
  /home/ant6/.local/lib/python2.7/site-packages/beprof/__init__.pyc
  /home/ant6/.local/lib/python2.7/site-packages/beprof/_version.py
  /home/ant6/.local/lib/python2.7/site-packages/beprof/_version.pyc
  /home/ant6/.local/lib/python2.7/site-packages/beprof/curve.py
  /home/ant6/.local/lib/python2.7/site-packages/beprof/curve.pyc
  /home/ant6/.local/lib/python2.7/site-packages/beprof/functions.py
  /home/ant6/.local/lib/python2.7/site-packages/beprof/functions.pyc
  /home/ant6/.local/lib/python2.7/site-packages/beprof/profile.py
  /home/ant6/.local/lib/python2.7/site-packages/beprof/profile.pyc
Proceed (y/n)? 
```

**Comment by grzanka** [comment]
So lets change priority to minor and postpone it to backlog.

**Comment by antnieszka** [comment]
This doesn't occur on Ubuntu 16.04 and Xubuntu is its fork, so... I'd close this one for now @grzanka 
The only thing is - we need to install python-pip and git to install beprof. More here: #97
